In [1]:

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [10]:
#Taking Data
x=np.array([1,23,34,314,14]).reshape(-1,1)
y=np.array([1,1,25,9,61])

In [11]:
#Fitting Model
model=LinearRegression().fit(x,y)

In [12]:
#Predicitng Y values for Given X values (b0+(b1*x))
y_pre=model.predict(x)

In [13]:
print("Predict Score: ",model.score(x,y_pre))
print("Normal Score : ",model.score(x,y))

Predict Score:  1.0
Normal Score :  0.047828461879053985


In [14]:
#Differnce Between Y predict and Given Y
print(y_pre)
print(y)

[22.56362587 21.65024307 21.19355167  9.56867972 22.02389967]
[ 1  1 25  9 61]


In [15]:
#Rechecking With Formula (b0+(b1*x))
print("b0: ",model.intercept_)
print("b1: ",model.coef_)
y_rc=model.intercept_+np.sum(model.coef_*x,axis=1)
print("Rechecked Y predict Values : ",y_rc)

b0:  22.605143267854007
b1:  [-0.0415174]
Rechecked Y predict Values :  [22.56362587 21.65024307 21.19355167  9.56867972 22.02389967]


In [16]:
#Predicitng Y values for Given X_new values (b0+(b1*x))
x_new=np.array([12,13,14,15,16]).reshape(-1,1)
y_new=model.predict(x_new)
print(x_new)
print(y_new)

[[12]
 [13]
 [14]
 [15]
 [16]]
[22.10693447 22.06541707 22.02389967 21.98238227 21.94086487]


In [17]:
print("New Predict Score: ",model.score(x_new,y_new))

New Predict Score:  1.0
