In [2]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
import numpy 
b=numpy.array([1,2,3])

In [6]:
print(b)

[1 2 3]


In [7]:
a.dtype.name

'int32'

In [8]:
b.dtype.name

'int32'

In [9]:
import numpy 
b2=numpy.array([1.2,4.2,3.6])

In [10]:
print(b2)

[1.2 4.2 3.6]


In [11]:
b2.dtype.name

'float64'

In [12]:
b2.itemsize

8

In [13]:
b2.size

3

In [14]:
type(b2)

numpy.ndarray

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.ones((1,2,3),dtype=np.int16)

array([[[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [19]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [1]:
import numpy as np
a=np.array([1,2,1,23,4,45,6,7,8,0,2,3,6,8,9])
value=np.unique(a)
print(value)

[ 0  1  2  3  4  6  7  8  9 23 45]


In [3]:
import numpy as np
a=np.array([1,2,1,23,4,45,6,7,8,0,2,3,6,8,9])
index=np.unique(a,return_index=True)
print(index)

(array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 23, 45]), array([ 9,  0,  1, 11,  4,  6,  7,  8, 14,  3,  5], dtype=int64))


In [4]:
import numpy as np
a=np.array([1,2,1,23,4,45,6,7,8,0,2,3,6,8,9])
count=np.unique(a,return_counts=True)
print(count)

(array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 23, 45]), array([1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1], dtype=int64))


In [9]:
a=np.arange(6).reshape((2,3))
print(a)
print(a.transpose())

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [41]:
a=np.array([1,2,3,4,5,67,8])
print(np.flip(a))

[ 8 67  5  4  3  2  1]


In [42]:
a=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(np.flip(a))

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [43]:
reverse=np.flip(a,axis=0)
print(reverse)

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [44]:
reverse=np.flip(a,axis=1)
print(reverse)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


In [45]:
a[1]=np.flip(a[1])
print(a)

[[ 0  1  2  3]
 [ 7  6  5  4]
 [ 8  9 10 11]]


In [46]:
a[:,1]=np.flip(a[:,1])
print(a)

[[ 0  9  2  3]
 [ 7  6  5  4]
 [ 8  1 10 11]]


In [47]:
a.flatten()

array([ 0,  9,  2,  3,  7,  6,  5,  4,  8,  1, 10, 11])

In [49]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
n=a*b
n

array([ 5, 12, 21, 32])

In [50]:
n=a+b
n

array([ 6,  8, 10, 12])

In [51]:
n=a-b
n

array([-4, -4, -4, -4])

In [52]:
n=a/b
n

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [53]:
np.add(a,b)

array([ 6,  8, 10, 12])

In [54]:
np.multiply(a,b)

array([ 5, 12, 21, 32])

In [55]:
np.subtract(a,b)

array([-4, -4, -4, -4])

In [56]:
np.divide(a,b)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [57]:
np.dot(a,b)

70

In [58]:
a.mean()

2.5

In [59]:
a.avg()

AttributeError: 'numpy.ndarray' object has no attribute 'avg'

In [60]:
a.std()

1.118033988749895

In [61]:
a.var()

1.25

In [68]:
a.std(axis=0)

1.118033988749895

In [67]:
a.mean(axis=0)

2.5