In [42]:
m=np.array=([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,1,0])
print("original vector:")
print(v)
print("original matrix:")
print(m)
result=np.empty_like(m)
for i in range(4):
    result[i,:]=m[i,:] + v
    print("\n after adding vector to each column")
    print(result)

TypeError: 'list' object is not callable

In [14]:
import numpy as np
def sum_matrix_elements(m):
    arr=np.array(m)
    element_sum=0
    for p in range(len(arr)):
        for q in range(len(arr[p])):
            if arr[p][q]==0 and p<len(arr)-1:
                arr[p+1][q]=0
            element_sum+=arr[p][q]
    return element_sum
m=[[1,1,0,2],
       [0,3,0,3],
       [1,0,4,4]]
print("original matrix:")
print(m)
print("sum:")
print(sum_matrix_elements(m))

original matrix:
[[1, 1, 0, 2], [0, 3, 0, 3], [1, 0, 4, 4]]
sum:
14


In [16]:
import numpy as np
nums=np.array([[3,2,np.nan,1],
              [10,12,10,9],
              [5,np.nan,1,np.nan]])
print("Original array:")
print(nums)
print("\n find the missing data of the said array:")
print(np.isnan(nums))

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

 find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [18]:
import numpy as np
n1=np.array([0.5,1.5,0.2])
n2=np.array([0.4999999999,1.500000000,0.2])
np.set_printoptions(precision=15)
print("original array:")
print(n1)
print(n2)
print("\n two arrays are equal or not:?")
print(n1==n2)
n1=np.array([0.5,1.5,0.23])
n2=np.array([0.4999999999,1.5000000001,0.23])
print("\n original array:")
np.set_printoptions(precision=15)
print(n1)
print(n2)
print("\n two arrays are equal or not:?")
print(np.equal(n1,n2))

original array:
[0.5 1.5 0.2]
[0.4999999999 1.5          0.2         ]

 two arrays are equal or not:?
[False  True  True]

 original array:
[0.5  1.5  0.23]
[0.4999999999 1.5000000001 0.23        ]

 two arrays are equal or not:?
[False False  True]


In [20]:
import numpy as np
n=np.arange(1,21)
print("one-dimensional array of single digit numbers:")
print(n)
n=np.arange(10,21)
print("\n one-dimensional array of two digit numbers:")
print(n)
n=np.arange(100,201)
print("\n one-dimensional array of three digit numbers:")
print(n)

one-dimensional array of single digit numbers:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 one-dimensional array of two digit numbers:
[10 11 12 13 14 15 16 17 18 19 20]

 one-dimensional array of three digit numbers:
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]


In [22]:
import numpy as np
print("create an array of shape(15,10):")
print("command-1")
print(np.arange(1,151).reshape(15,10))
print("\n command-2")
print(np.arange(1,151).reshape(-1,10))
print("\n command-3")
print(np.arange(1,151).reshape(15,-1))

create an array of shape(15,10):
command-1
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]]

 command-2
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70

In [23]:
import numpy as np
np.random.seed(10)
print(np.random.rand(40))

[0.771320643266746 0.020751949359402 0.633648234926275 0.748803882538612
 0.49850701230259  0.224796645530848 0.198062864759624 0.760530712198959
 0.169110836562535 0.08833981417401  0.685359818367797 0.953393346194937
 0.003948266327914 0.512192263385777 0.812620961652114 0.612526066829388
 0.7217553174318   0.291876068170633 0.917774122512943 0.714575783397691
 0.542544368011261 0.142170047601527 0.373340760051469 0.674133615066345
 0.441833174422996 0.434013993333294 0.617766978469317 0.513138242554391
 0.650397181931467 0.601038953404544 0.805223196832746 0.521647152393634
 0.908648880808668 0.319236088988545 0.090459349270907 0.300700056636203
 0.11398436186355  0.828681326307677 0.04689631938925  0.626287148311393]


In [24]:
import numpy as np
np.random.seed(20)
cbrt=np.cbrt(7)
nd1=200
print(cbrt*np.random.randn(10,4)+nd1)

[[201.69082669736346 200.3746763082702  200.68394275021677
  195.51750123129818]
 [197.92478991563303 201.07066048488275 201.79714021459858
  198.12823310277952]
 [200.96238963339914 200.77744291067876 200.61875865227867
  199.05613893807728]
 [198.48492638364303 198.38860811141893 197.55239946005003
  200.47003620983824]
 [199.9154583876559  202.99877319355295 202.01069856971475
  200.77735483308504]
 [199.67739161408255 193.89831807071494 202.14273592752286
  202.54951299405823]
 [199.53450968631876 199.75126019761723 199.791457270905
  202.97687756587686]
 [200.24634412660365 196.0460693352411  198.3061125324022
  197.88701546225133]
 [201.7845091237894  203.94032834458278 198.21152802602944
  196.9144607143198 ]
 [201.0082480992413  197.03285103581035 200.6305276348363
  197.82590294139914]]


In [29]:
import numpy as np
print("Generate a uniform random sample with replacement:")
print(np.random.choice(7,5))
print("\n Generate a uniform random sample without replacement:") 
print(np.random.choice(7,5,replace=False))
print("\n Generate a non-uniform random sample with replacement:") 
print(np.random.choice(7, 5, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))
print("\n Generate a uniform random sample without replacement:") 
print(np.random.choice(7, 5, replace=False, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1])) 

Generate a uniform random sample with replacement:
[6 0 0 2 3]

 Generate a uniform random sample without replacement:
[0 1 3 6 4]

 Generate a non-uniform random sample with replacement:
[1 4 0 4 1]

 Generate a uniform random sample without replacement:
[1 3 6 0 4]


In [30]:
import numpy as np
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last rows of the said array:")
nums[[0,-1],:]=nums[[-1,0],:]
print(nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [31]:
import numpy as np
nums = np.zeros(shape=(5, 6), dtype='int')
print("Original array:")
print(nums)
nums[::2, ::2] = 3
nums[1::2, ::2] = 7
print("\nNew array:")
print(nums)

Original array:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

New array:
[[3 0 3 0 3 0]
 [7 0 7 0 7 0]
 [3 0 3 0 3 0]
 [7 0 7 0 7 0]
 [3 0 3 0 3 0]]


In [32]:
import numpy as np  
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
print("\nSort the said array by row in ascending order:")
print(np.sort(nums))
print("\nSort the said array by column in ascending order:")
print(np.sort(nums, axis=0))

Original array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Sort the said array by row in ascending order:
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Sort the said array by column in ascending order:
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


In [33]:
import numpy as np  
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
n = 5
print("\nElements of the said array greater than",n)
print(nums[nums > n])
n = 6
print("\nElements of the said array less than",n)
print(nums[nums < n])

Original array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Elements of the said array greater than 5
[5.54 7.99 6.99 9.29]

Elements of the said array less than 6
[5.54 3.38 3.54 4.38 1.54 2.39]


In [34]:
import numpy as np
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 8.32, 6.99],
              [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
n = 8.32
r = 18.32
print("\nReplace elements of the said array which are equal to ",n,"with",r)
print(np.where(nums == n, r, nums))
print("\nReplace elements with of the said array which are less than",n,"with",r)
print(np.where(nums < n, r, nums))
print("\nReplace elements with of the said array which are greater than",n,"with",r)
print(np.where(nums > n, r, nums))

Original array:
[[5.54 3.38 7.99]
 [3.54 8.32 6.99]
 [1.54 2.39 9.29]]

Replace elements of the said array which are equal to  8.32 with 18.32
[[ 5.54  3.38  7.99]
 [ 3.54 18.32  6.99]
 [ 1.54  2.39  9.29]]

Replace elements with of the said array which are less than 8.32 with 18.32
[[18.32 18.32 18.32]
 [18.32  8.32 18.32]
 [18.32 18.32  9.29]]

Replace elements with of the said array which are greater than 8.32 with 18.32
[[ 5.54  3.38  7.99]
 [ 3.54  8.32  6.99]
 [ 1.54  2.39 18.32]]


In [35]:
import numpy as np  
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 8.32, 6.99],
              [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
print("\nNew array of equal shape and data type of the said array filled by 0:")
print(np.zeros_like(nums))

Original array:
[[5.54 3.38 7.99]
 [3.54 8.32 6.99]
 [1.54 2.39 9.29]]

New array of equal shape and data type of the said array filled by 0:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
import numpy as np  
nums = np.array([[[1, 5, 2, 1],
               [4, 3, 5, 6],
               [6, 3, 0, 6],
               [7, 3, 5, 0],
               [2, 3, 3, 5]],
              
              [[2, 2, 3, 1],
               [4, 0, 0, 5],
               [6, 3, 2, 1],
               [5, 1, 0, 0],               
               [0, 1, 9, 1]],
              
              [[3, 1, 4, 2],
               [4, 1, 6, 0],
               [1, 2, 0, 6],
               [8, 3, 4, 0],               
               [2, 0, 2, 8]]]) 
print("Array:")
print(nums)

Array:
[[[1 5 2 1]
  [4 3 5 6]
  [6 3 0 6]
  [7 3 5 0]
  [2 3 3 5]]

 [[2 2 3 1]
  [4 0 0 5]
  [6 3 2 1]
  [5 1 0 0]
  [0 1 9 1]]

 [[3 1 4 2]
  [4 1 6 0]
  [1 2 0 6]
  [8 3 4 0]
  [2 0 2 8]]]


In [37]:
import numpy as np 
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last columns of the said array:")
new_nums = nums[:, ::-1]
print(new_nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last columns of the said array:
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [38]:
import numpy as np
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])
print("Original array:")
print(nums)
print("\nSwap rows and columns of the said array in reverse order:")
new_nums = print(nums[::-1, ::-1])
print(new_nums)

Original array:
[[[ 1  2  3  4]
  [ 0  1  3  4]
  [90 91 93 94]
  [ 5  0  3  2]]]

Swap rows and columns of the said array in reverse order:
[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]
None


In [39]:
import numpy as np 
nums1 = np.array([[2, 5, 2],
              [1, 5, 5]])
nums2 = np.array([[5, 3, 4],
              [3, 2, 5]])
print("Array1:") 
print(nums1)
print("Array2:") 
print(nums2)
print("\nMultiply said arrays of same size element-by-element:")
print(np.multiply(nums1, nums2))

Array1:
[[2 5 2]
 [1 5 5]]
Array2:
[[5 3 4]
 [3 2 5]]

Multiply said arrays of same size element-by-element:
[[10 15  8]
 [ 3 10 25]]
