In [16]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [17]:
x=np.array([[51,22],[17,14],[21,19],[15,22],[119,117]])
y=np.array([7,3,5,19,6])

In [18]:
model=LinearRegression().fit(x,y)

In [19]:
y_pre=model.predict(x)

In [20]:
print("Predict Score: ",model.score(x,y_pre))
print("Normal Score : ",model.score(x,y))

Predict Score:  1.0
Normal Score :  0.1779995524007043


In [21]:
#Differnce Between Y predict and Given Y
print(y_pre)
print(y)

[ 4.05849014  9.18363273  9.24069284 10.86254071  6.65464358]
[ 7  3  5 19  6]


In [22]:
#Rechecking With Formula (b0+(b1*x))
print("b0: ",model.intercept_)
print("b1: ",model.coef_)
y_rc=model.intercept_+np.sum(model.coef_*x,axis=1)
print("Rechecked Y predict Values : ",y_rc)

b0:  10.120072549133624
b1:  [-0.1890014   0.16261315]
Rechecked Y predict Values :  [ 4.05849014  9.18363273  9.24069284 10.86254071  6.65464358]


In [23]:
#Predicitng Y values for Given X_new values (b0+(b1*x))
x_new=np.array([12,13,14,15,16,18,19,20,21,22]).reshape(-1,2)
y_new=model.predict(x_new)
print(x_new)
print(y_new)

[[12 13]
 [14 15]
 [16 18]
 [19 20]
 [21 22]]
[ 9.9660266   9.91325009 10.02308672  9.7813088   9.72853228]


In [24]:
print("New Predict Score: ",model.score(x_new,y_new))

New Predict Score:  1.0
