In [1]:
#Packages And Librarys
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [2]:
#Taking Data
x=np.array([1,4,5,14,41]).reshape(-1,1)
y=np.array([89,33,3,11,1])

In [3]:
T=PolynomialFeatures(degree=2,include_bias=False)
T.fit(x)
x_=T.transform(x)
model=LinearRegression(fit_intercept=False).fit(x_,y)
print(x_)

[[1.000e+00 1.000e+00]
 [4.000e+00 1.600e+01]
 [5.000e+00 2.500e+01]
 [1.400e+01 1.960e+02]
 [4.100e+01 1.681e+03]]


In [4]:
#Predicitng Y values for Given X values (b0+(b1*x))
y_pre=model.predict(x_)

In [5]:
print("Predict Score: ",model.score(x_,y_pre))
print("Normal Score : ",model.score(x_,y))

Predict Score:  1.0
Normal Score :  -0.5354791654577327


In [6]:
#Differnce Between Y predict and Given Y
print(y_pre)
print(y)

[ 2.64888539  9.79728985 11.91400743 24.97757765 -0.49010168]
[89 33  3 11  1]


In [7]:
#Rechecking With Formula (b0+(b1*x))
print("b0: ",model.intercept_)
print("b1: ",model.coef_)
y_rc=model.intercept_+np.sum(model.coef_*x_,axis=1)
print("Rechecked Y predict Values : ",y_rc)

b0:  0.0
b1:  [ 2.71540637 -0.06652098]
Rechecked Y predict Values :  [ 2.64888539  9.79728985 11.91400743 24.97757765 -0.49010168]
